# Generated by Django 5.2.13 on 2026-06-02 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_mentioned_users_commentnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='guest_email',
            field=models.EmailField(blank=True, default='', help_text='游客邮箱（未登录用户必填，不会公开显示）', max_length=254, verbose_name='guest email'),
        ),
        migrations.AddField(
            model_name='comment',
            name='guest_name',
            field=models.CharField(blank=True, default='', help_text='游客昵称（未登录用户必填）', max_length=50, verbose_name='guest name'),
        ),
        migrations.AddField(
            model_name='comment',
            name='guest_website',
            field=models.URLField(blank=True, default='', help_text='游客网站（选填）', verbose_name='guest website'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
