# Generated by Django 5.2.13 on 2026-05-28 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bloguser_options_remove_bloguser_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='用户头像', null=True, upload_to='avatars/%Y/%m/', verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='bio',
            field=models.TextField(blank=True, help_text='个人简介', max_length=500, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='following'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='github',
            field=models.CharField(blank=True, help_text='GitHub用户名', max_length=100, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='location',
            field=models.CharField(blank=True, help_text='所在地', max_length=100, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter用户名', max_length=100, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='website',
            field=models.URLField(blank=True, help_text='个人网站', verbose_name='website'),
        ),
    ]
