# Generated by Django 5.2.13 on 2026-05-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogsettings_color_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='portfolio_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='portfolio_education',
            field=models.TextField(blank=True, default='', help_text='Education in Markdown', verbose_name='Education (Markdown)'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='portfolio_experience',
            field=models.TextField(blank=True, default='', help_text='Work experience in Markdown', verbose_name='Experience (Markdown)'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='portfolio_github',
            field=models.URLField(blank=True, default='', verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='portfolio_hero_subtitle',
            field=models.TextField(blank=True, default='', help_text='Short tagline below the title', max_length=500, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='portfolio_hero_title',
            field=models.CharField(blank=True, default='', help_text='Homepage hero title, e.g. your name', max_length=200, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='portfolio_linkedin',
            field=models.URLField(blank=True, default='', verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='portfolio_skills',
            field=models.TextField(blank=True, default='', help_text='JSON array: [{"name":"Python","icon":"...","desc":"..."},...]', verbose_name='Skills (JSON)'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='color_scheme',
            field=models.CharField(choices=[('apple-dark', 'Apple Dark - Black+Green'), ('purple', '紫色主题 - Purple Dream'), ('blue', '蓝色主题 - Ocean Blue'), ('green', '绿色主题 - Forest Green'), ('orange', '橙色主题 - Sunset Orange'), ('pink', '粉色主题 - Cherry Blossom'), ('red', '红色主题 - Ruby Red'), ('indigo', '靛蓝主题 - Midnight Indigo'), ('teal', '青色主题 - Teal Wave')], default='apple-dark', help_text='选择网站的主题配色方案', max_length=20, verbose_name='配色方案'),
        ),
    ]
