# Generated by Django 5.2.13 on 2026-05-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogsettings_portfolio_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='文章摘要，留空则自动截取文章内容', max_length=500, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='文章特色图片', null=True, upload_to='articles/%Y/%m/', verbose_name='featured image'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_description',
            field=models.TextField(blank=True, help_text='搜索引擎优化描述，留空则自动截取文章内容', max_length=500, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='搜索引擎优化关键词，用逗号分隔', max_length=200, verbose_name='SEO keywords'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, help_text='搜索引擎优化标题，留空则使用文章标题', max_length=200, verbose_name='SEO title'),
        ),
    ]
