# Generated by Django 5.2.13 on 2026-06-02 18:04

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_excerpt_article_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='resume_age',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='resume_avatar',
            field=models.ImageField(blank=True, help_text='建议尺寸 200x200 像素', null=True, upload_to='resume/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='resume_education',
            field=models.CharField(blank=True, choices=[('college', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('phd', '博士')], default='', max_length=20, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='resume_job_expectation',
            field=models.TextField(blank=True, default='', help_text='如：Python开发工程师 | 深圳/上海 | 25-35K', verbose_name='求职期望'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='resume_job_status',
            field=models.CharField(blank=True, choices=[('employed', '在职-考虑机会'), ('resigned', '离职-随时到岗'), ('student', '在校学生')], default='resigned', max_length=20, verbose_name='求职状态'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='resume_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='resume_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='resume_recent_projects',
            field=mdeditor.fields.MDTextField(blank=True, default='', help_text='支持Markdown格式', verbose_name='最近项目经历'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='resume_strengths',
            field=models.TextField(blank=True, default='', help_text='每行一条优势，前端自动转为标签展示', verbose_name='个人优势'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='resume_wechat',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='微信号'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='resume_work_experience',
            field=models.TextField(blank=True, default='', help_text='JSON格式，包含公司、职位、时间段和项目列表', verbose_name='工作经历'),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='resume_years_experience',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='工作经验(年)'),
        ),
    ]
